### ISSUE TITLE
请问如何只显示一级标题和二级标题

### ISSUE THREAD

**Issue by ffywhxf** [sethyuan/logseq-plugin-tocgen#11]
如题
一级标题和二级标题之间没有缩进

**Comment by sethyuan** [comment]
@ffywhxf 插件是通过缩进来判断目录层级的，没有缩进会存在不好处理的歧义。例如，先出现一个二级标题再出现一个一级标题，这种情况下要如何组织目录呢？又或者，我没有用一级标题，全都是用的二级和三级。各种情况会导致处理复杂度上升但又没有带来收益。Logseq本来就是一个大纲型笔记，使用缩进来表现层级关系非常正常。

如果你仅是希望在阅读时没有那么多缩进影响视觉效果的话，你可以尝试我的另一个插件： https://github.com/sethyuan/logseq-plugin-doc
在插件市场里也能下载到，叫Doc View Exporter。它提供了一个只读的文档视图，可以认为是一种预览，并提供了导出的功能。
