### ISSUE TITLE
logseq更新到0.5.9后，因其lazy loading导致目录不到转跳到页面

### ISSUE THREAD

**Issue by ffywhxf** [sethyuan/logseq-plugin-tocgen#12]
如题，
长文章直接点后边的章节，不能转跳了。

**Comment by sethyuan** [comment]
我还真没注意过长文章的情况。等稍后有空我先造个长文章看看现在的效果是什么样的。

**Comment by sethyuan** [comment]
@ffywhxf 我看了长文章下的效果了，很可惜，就目前的插件框架来说是没有办法解决的，只能将这个问题汇报到Logseq那儿。

**Comment by sethyuan** [comment]
@ffywhxf 我知会给Logseq团队了，他们说会处理这个问题。

**Comment by ffywhxf** [comment]
感谢作者您的回复。
Logseq团队应该也注意到了，有了lazy loading，当前页面的搜索结果，也不能转跳了。

**Comment by hdg8087** [comment]
假如我有1000个页面，每个都想要页内目录，怎么办呢？
总不能都写在Contents中吧？Contents中的位置也很有限、很宝贵的。

**Comment by sethyuan** [comment]
> 假如我有1000个页面，每个都想要页内目录，怎么办呢？ 总不能都写在Contents中吧？Contents中的位置也很有限、很宝贵的。

虽然你的问题和这个issue不相关，但你可以尝试像我一样，在Contents中建一个动态TOC，它会随页面变化而变化。详见README中的动画演示。
