### ISSUE TITLE
Recognize heading using metadata instead of `#`

### ISSUE THREAD

**Issue by nhan000** [sethyuan/logseq-plugin-tocgen#13]
When set a block as a heading in Logseq, I right click a block -> `convert to a heading`. Logseq then add `heading:: true` as a property for that block.

I prefer this over using `#` because the heading will automatically change its level base on how deep it is nested, so when I move the blocks around I don't have to change the number of `#`

This heading currently is not supported by tocgen plugin, so when I use `{{renderer :tocgen, *, 2, h}}` it doesn't work.

Could you please add support for heading based on the metadata? Thanks a lot!

**Comment by sethyuan** [comment]
Great suggestion! Personally I never used the heading feature you mentioned. I think it’s doable, I’ll let you know when I have it implemented.

**Comment by sethyuan** [comment]
@nhan000 It's implemented.

**Comment by nhan000** [comment]
https://user-images.githubusercontent.com/85216095/151561062-d7f7f595-d99d-4de6-82cb-c85431a8130f.mp4

I've tried it a few times and it's not working for me. When I add `h` the rendered TOC is really off.

For a mock page that have a few and simple blocks, at the first few tries it rendered correctly, but then it no longer works as expected.
For a real page that I use for my university coursework, it's not working at all.

**Comment by sethyuan** [comment]
Thanks for providing this detailed screenshot! I see you're using links from PDF files. I'll investigate.

**Comment by sethyuan** [comment]
Hi @nhan000 , I tried PDF links as you demonstrated but found no problem at all. I'm wondering if it could be a compatibility issue with other plugins?

Also, in your case, it's more appropriate to use `[[]]` as page name instead of `*`, `*` means active main page, which change depending how you are displaying the page, `[[]]` instead, will always follow the page the TOC belongs to.

**Comment by sethyuan** [comment]
BTW, what version of Logseq are you using?

**Comment by nhan000** [comment]
I'm using 0.5.9 official beta (not nightly)
I've turned off other plug-ins, closed and reopened Logseq, and still see the buggy behavior. (let me know if I have to uninstall them to test)
I've change `*` to `[[]]` and it didn't help.
Btw, I don't understand what's the difference between `[[]]` and `*`. `*` means active main page => when I zoom in a block the TOC will be rendered differently (only display TOC for the zoomed in block)?

**Comment by sethyuan** [comment]
I'm using 0.5.9 too. Is it possible you give me a copy of the page that have this issue?

Regarding the `*` behavior, you can refer to the README, which I just updated to reflect its typical usage.

**Comment by nhan000** [comment]
You can download a copy of my Graph that has the 2 pages (together with the pdf and annotations) [here](https://drive.google.com/drive/folders/1vPTHyy5L7h_ToiBC-bMEai_ZzdPV0-yI?usp=sharing)

Okay I think I understand the dynamic TOC now. Is it that if we have the dynamic TOC on the right sidebar, in the Contents page, it will automatically renders the TOC for the page opened in the main panel? That's really cool! However, it also didn't work for me ha ha. Please test the dynamic TOC also with the graph I sent you.

thanks a lot for your time fixing this for me!

**Comment by sethyuan** [comment]
Your copy was very helpful in debugging the problem. I've located the issue and fixed it, please give new version a try.

Regarding the dynamic TOC, yes, it changes automatically depending on what page you're currently working on and, no, you don't need to change default settings if you specify all the parameters.

**Comment by nhan000** [comment]
works amazing! :) Thank you so so much!

**Comment by sethyuan** [comment]
Glad I can help!
