### ISSUE TITLE
大纲目录的新功能需求，大佬看看值不值得淦一个插件

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#14]
[Create a title preview to quickly adjust the title of the line when writing - Feature Requests - Logseq](https://discuss.logseq.com/t/create-a-title-preview-to-quickly-adjust-the-title-of-the-line-when-writing/5474)
我提了一个功能，大佬看看值不值得淦一个插件
需求描述：

在观看视频和阅读文章时，记笔记，通常需要根据文章的逻辑，不断在不同标题级别下，摘录一些关键语录，但行数太多，看不到顶部的标题，无法快速切换到之前的标题下，进行输入。因此，我觉得需要在当前输入的行，使用快捷键，快速调出一个大纲标题预览悬浮窗口，以便指导，快速调整当前输入行，所在的大纲标题级别。

一些截图：

1、大纲标题预览窗口的设计

![image](https://user-images.githubusercontent.com/15712822/153759882-7728a42c-c1b6-4b2e-af58-b30d961a1675.png)

2.更改书写行的大纲级别时，这个预览将根据大纲级别自动跳转
![image](https://user-images.githubusercontent.com/15712822/153759887-f5a6e9b7-ca7d-4c34-bb98-1bf18a03fcc0.png)

谢谢

**Comment by aiyou9** [comment]
或者在页面顶部用面包屑导航，或导航键提醒？

**Comment by sethyuan** [comment]
意思是想快速定位到某个标题在它下面进行输入？那是不是可以通过将TOC打开至右侧边栏来实现？你可以shift点击TOC的小圆点将其打开至侧边栏。

**Comment by aiyou9** [comment]
与 #15 类似的目的，但是更为快捷，目光不离开当前页面，可能码字更爽，

如果点击这个issue #14 描述的弹出窗口中，显示当前页面的目录标题，并支持与主窗口一样的编辑功能，更适于梳理写作的大纲逻辑。

有一个参考插件，[logseq-plugin-link-preview ](https://github.com/pengx17/logseq-plugin-link-preview)
可预览logseq页面/标签，并且可像logseq主窗口一样编辑。

![image](https://user-images.githubusercontent.com/15712822/154072786-ab245657-a957-4c8d-b7df-f73c23c04606.png)

看大佬你，还有一个插件 [logseq-plugin-wrap](https://github.com/sethyuan/logseq-plugin-wrap)，可以提供含有功能按钮的悬浮工具栏

是否可以结合起来，给一个带功能按钮的悬浮窗

在写作中，快速调整，已写内容的标题层级，加快写作逻辑的梳理与调整

初步设计的原型设计：

![image](https://user-images.githubusercontent.com/15712822/154082485-93d0109f-4de2-4f0c-8ecb-c4550df747f5.png)

**Comment by sethyuan** [comment]
可能我没有理解到，我不明白为什么整理层级与当前输入行有关联？我觉得这是两种不同意图的操作。速记的时候你不需要太多考虑层级的问题，就只管记，全部记录好后再来整理一遍大纲。

另外你说的这些整理层级的功能都是Logseq自带就有的功能，我觉得没有必要在插件中重新实现一遍。

**Comment by aiyou9** [comment]
嗯，确实，记录与整理融合在一起，确实不好，我对logseq的使用和理解还不够。
