### ISSUE TITLE
功能建议：实时聚焦当前输入行，右边目录能自动定位，指示当前输入行所在目录层级

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#15]

**Comment by sethyuan** [comment]
你想象的效果具体一点是什么样的呢？有没有示意图之类的？现在的描述太模糊了，我没太理解到。

**Comment by sethyuan** [comment]
OK，明白了，很清晰。我也觉得这是一个很有用的功能，我想想看怎么实现，尽量把它做出来。

**Comment by aiyou9** [comment]
> OK，明白了，很清晰。我也觉得这是一个很有用的功能，我想想看怎么实现，尽量把它做出来。
👍大佬强，logseq还没发布稳定版，不一定好实现，大佬，加油。

**Comment by sethyuan** [comment]
@aiyou9 我还没做完呢，你怎么就给关了？ 😂

**Comment by sethyuan** [comment]
已经实现了，v1.9.0，样式可自定义，请参看README。 @aiyou9

**Comment by willzhqiang** [comment]
请问每个标题后面显示的h1 h2都是怎么做到的呀，有什么插件吗？ 因为标题之间的差别不大，能像Bear那样显示这个是几级的标题，确实也很方便，我看你们的截图都有，但我没找到是哪个插件实现的？

**Comment by sethyuan** [comment]
@willzhqiang 有主题支持这种显示，可以翻翻。

**Comment by willzhqiang** [comment]
> @willzhqiang 有主题支持这种显示，可以翻翻。

https://github.com/pengx17/logseq-dev-theme
感谢，找到了，目前看来这个是支持的。
