### ISSUE TITLE
功能需求，toc监听页面上的标题或块层级的展开与收起

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#18]
当页面中标题或块层级，通过快捷键，或手动点击，进行展开与收起时，TOC也能够实时监听，实时更新

**Comment by sethyuan** [comment]
我不赞同将TOC和正文的折叠状态做同步，内容可以同步，但折叠状态不适合同步。例如我折叠TOC的某个层级是为了节省侧边栏空间，但这不代表我也想折叠正文。

**Comment by aiyou9** [comment]
> 我不赞同将TOC和正文的折叠状态做同步，内容可以同步，但折叠状态不适合同步。例如我折叠TOC的某个层级是为了节省侧边栏空间，但这不代表我也想折叠正文。

嗯，就像网盘同步一样，有单方向的同步，比如在页面中折叠块，toc自动监听折叠，但是在toc折叠，页面不会随着折叠。
如果可以，可以作为设置中，使用者自己选择，三种选项：

1、页面与TOC双向同步折叠与展开；
2、单向的，页面折叠，TOC同步折叠，但是TOC折叠时，页面不跟随折叠；
3、单向的，TOC折叠，页面同步折叠，但是页面折叠时，TOC不跟随折叠；

# 或者在右下角，回到顶部的TOP悬浮按钮上面，再加一个快捷按钮，用于快速展开与折叠TOC？监听页面的折叠状态，确实不方便，还是快捷键，一键展开与收起#

具体我在实践过程中，再总结一下，主要目的，是为了能够在页面中，不用滚动，就能获取标题和前后段落等不同层次的上下文，作为调整当前输入块层级的参考。

**Comment by aiyou9** [comment]
> 

这个展开与收起快捷按钮，对TOC展示页面所有层级 ，比展示#h标题层级，更有用，可能需要给两个快捷按钮，一个按钮是点击一次，展开一级，，一个是点击一次收起一级，两个方向，实现通过点击，进行来回展开与收起与循环操作。

**Comment by sethyuan** [comment]
你说的是类似这种展开效果吗？

![image](https://user-images.githubusercontent.com/3410293/156762341-c328f2ed-c35f-4a8c-ac0c-6dd8411d9989.png)

**Comment by aiyou9** [comment]
这个图用logseq画的？后面我也用图来描述，学习了

**Comment by sethyuan** [comment]
不对，咱们好像不在一个频道上，我还是没有理解你想要的效果和为什么要这样做？
至于图，我是用[Excalidraw](https://excalidraw.com/)画的。

**Comment by aiyou9** [comment]
感谢，用折叠线实现，确实比较好，太自动化，不好适应更广泛的需求
