### ISSUE TITLE
BUG：当前最新版TOC，显示#h标题，如果#h标题，移入到其他非标题块的下一级，TOC不显示

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#19]
可能也不算bug
毕竟#h标题一般也不会在非标题块的下一层级
![Snipaste_2022-03-04_19-42-10](https://user-images.githubusercontent.com/15712822/156757425-76c4cd2d-86ff-4a25-bd49-f549f1ef4e2b.png)

**Comment by sethyuan** [comment]
嗯，插件原本的行为就是这样设计的。你不能把标题放在正文里面，这很奇怪。
