### ISSUE TITLE
Markdown links not rendered correctly

### ISSUE THREAD

**Issue by Bad3r** [sethyuan/logseq-plugin-tocgen#2]
If a bullet or a header contains a link e.g. `[]()` It's not rendered correctly

![](https://user-images.githubusercontent.com/25513724/147495411-d32f965f-9d8b-42d6-aad4-9ac6c0f7242a.png)

**Comment by sethyuan** [comment]
Thanks for reporting! I realized that my processing is not rigorous enough, specifically I didn't handle any markdown beside headings, though I did handle page/block references. I'll work on this.

**Comment by sethyuan** [comment]
@Bad3r  Done, markdown handling is implemented. Please check the newest version.

**Comment by Bad3r** [comment]
@sethyuan Awesome! Thank you! Just tested it and can confirm its working as expected.
