### ISSUE TITLE
BUG：TOC的any模式，如果文字中有数字+英文括号+空格，TOC无法显示，且电脑卡

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#20]
![Snipaste_2022-03-04_21-29-32](https://user-images.githubusercontent.com/15712822/156772008-f10a256d-f7d0-4c99-a602-d0bfd37f38c7.png)

**Comment by sethyuan** [comment]
收到，我排查下。

**Comment by sethyuan** [comment]
@aiyou9 已找到原因，是因为 1) 这种识别成了markdown语法的有序列表，之前对列表的处理有问题导致的。已fix，不过有序列表会被统一渲染为 `1.` 这种样子。

**Comment by aiyou9** [comment]
> @aiyou9 已找到原因，是因为 1) 这种识别成了markdown语法的有序列表，之前对列表的处理有问题导致的。已fix，不过有序列表会被统一渲染为 `1.` 这种样子。

ok，已测试
