### ISSUE TITLE
Scrolls back to TOC when clicking any content

### ISSUE THREAD

**Issue by KKKIIO** [sethyuan/logseq-plugin-tocgen#21]
Plugin version: v1.10.2
LogSeq version: 0.6.1

With the plugin turned on, when I click on a header or text, the editor almost always scrolls back to the corresponding TOC item.

**Comment by sethyuan** [comment]
This is a feature implemented to help track "under what block you are currently editing". I see you don't like it, do you have any particular reasons?

**Comment by sethyuan** [comment]
@KKKIIO Issue fixed, it was a bad decision to add scroll behavior, I have removed it. Please give new version a try.

**Comment by KKKIIO** [comment]
Thanks for getting back to me so quickly! Now it works as I expected.

**Comment by aiyou9** [comment]
> @KKKIIO问题已修复，添加滚动行为是一个错误的决定，我已经删除了它。请尝试新版本。

引起的问题严重吗？个人觉得，这个功能还是有应用场景和价值的，能不能拆分出来，或者提供开关，用于开启这个功能？

**Comment by sethyuan** [comment]
问题很严重，影响了一些正常使用的场景。
