### ISSUE TITLE
Clicking the folding line should expand the collapsed state?

### ISSUE THREAD

**Issue by nhan000** [sethyuan/logseq-plugin-tocgen#22]
If the TOC is expanded, clicking the folding line collapses the TOC, which is great.

But clicking it again doesn't expand the folded blocks.

I'd expect clicking the folding lines would toggle collapsing the TOC.

**Comment by sethyuan** [comment]
Somehow I missed this issue report. 😅  It's fixed now.

**Comment by nhan000** [comment]
works great! thanks a lot!

**Comment by nhan000** [comment]
works great! thanks a lot!
