### ISSUE TITLE
Typo in default setting file

### ISSUE THREAD

**Issue by oriofdarkforest** [sethyuan/logseq-plugin-tocgen#23]
The default setting file looks like this:
```
{
  "disabled": false,
  "defaultLevels": 1,
  "defaultCollaped": false,
  "defaultHeadingType": "any",
  "hideBackTop": false,
  "noPageJump": false
}
```
`defaultCollaped` should be `defaultCollapsed` or it will not work by changing it to `true`
It also appears in your `readme.md`

Thank you for your great work. Love this plugin.

您好, 默认的设置文件有一个单词错误 `defaultCollaped` -> `defaultCollapsed`
谢谢您的插件, 非常好用

**Comment by sethyuan** [comment]
Oops, my bad. Thanks for reporting, I updated the plugin.
