### ISSUE TITLE
功能探讨：页面或标签，是否能在目录中，也是页面或标签的形式，方便鼠标悬停预览，与点击跳转

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#24]
主要探讨问题：在目录中，是否可以增加双链链接，在大纲目录上，加上双链，增加大纲目录的三维深度，为撰写文章时，辅助凝练大纲，提供素材，以此打开思路？

场景1
对标题打标签，对相关内容，进行预览，跳转，进一步为凝练标题，提供素材
![image](https://user-images.githubusercontent.com/15712822/160263490-96dba52a-a91f-4608-8257-d7b2f9c2bef1.png)

![image](https://user-images.githubusercontent.com/15712822/160263619-3eee0c24-9ecf-485c-b778-22a28922f031.png)

场景2
为了使用双链，以下写法，能够兼容大纲层级，toc是否可以支持页面的双链
![image](https://user-images.githubusercontent.com/15712822/160263695-33ded249-67e2-433f-9316-319301539fd0.png)

**Comment by sethyuan** [comment]
这个目前Logseq的插件库还实现不了，没有显示悬停预览的API。等以后有支持的时候可以考虑一下。

**Comment by aiyou9** [comment]
嗯，插件能在目录的标题中，添加双链吗？

**Comment by sethyuan** [comment]
这个应该不叫双链，就是页面的链接。另外虽然有可能可以添加链接，但是与TOC的用途不符，使用上会有冲突，比如整个标题就是一个页面链接，那么点击时是定位到块自身还是跳转到链接去呢？个人不建议加这个功能。

**Comment by aiyou9** [comment]
> 那么点击时是定位到块自身还是跳转

toc generate 目前，已经对跳转页面与聚焦模式，区分了，目录大纲支持打标签等双链，个人觉得还是有价值，辅助文章撰写，有一个高层次的视角，同时，通过标签，快速添加相关素材，通过双链的预览，与素材的整理，快速提炼标题。
主要想法，是通过支持双链的目录大纲，与页面区别开了，相当于，提升一个层次，从更高的角度，思考，但是又能，通过双链的关联，实现每个标题的原子化，高细腻度的素材关联与思考，而不是在写作页面里，进行一些素材的查询整理，避免太多的干扰。

这些方面，目前不是一个广泛的需求，因此，此issue先关闭了
