### ISSUE TITLE
[feature request🙋‍♂️] hide the display of footnotes

### ISSUE THREAD

**Issue by TITC** [sethyuan/logseq-plugin-tocgen#25]
你好，感谢提供了如此方便的插件。

但我在使用过程中遇到了一些问题，logseq支持Markdown的footnotes
![脚注](https://discuss.logseq.com/uploads/default/original/2X/e/e40fd46cd7d4a156eef20bb1808f3f12c9061fa1.png)

但是logseq不支持自动增加序号，因此我一般用title作为显示
![image](https://user-images.githubusercontent.com/35098797/163680539-8382379f-42e4-4540-8dbf-4e6e8f564b50.png)
但侧边栏看起来就会很难受
![image](https://user-images.githubusercontent.com/35098797/163680552-f51f8d49-f878-4ee9-af5c-983ce0495f8b.png)
有没有啥办法把这部分隐藏掉？

**Comment by sethyuan** [comment]
是可以做到的，明天有空我看看。

**Comment by sethyuan** [comment]
已经实现了，请更新下版本看看。

**Comment by TITC** [comment]
可以了，很感谢
