### ISSUE TITLE
[feature request🙋‍♂️] add an regular expression option for auto ignore

### ISSUE THREAD

**Issue by TITC** [sethyuan/logseq-plugin-tocgen#26]
很感谢你提供的更新 https://github.com/sethyuan/logseq-plugin-tocgen/issues/25#issue-1206138503 ，关于脚注现在表现很好。

但是logseq里还有其他的插件/功能，功能也是在子集标题上做一些触发操作。

譬如

![image](https://user-images.githubusercontent.com/35098797/163777289-9db68d21-1673-45a3-b62a-3734f8d45ac9.png)

`{{renderer :todomaster}}`
想问下这个能不能在配置文件中增加一个选项，不显示符合某些正则表达式的字符串？正则可以用户自己写。

**Comment by sethyuan** [comment]
我发了新版，针对宏渲染做了隐藏。你再看看。

**Comment by TITC** [comment]
棒
