### ISSUE TITLE
Feature request: Render Latex

### ISSUE THREAD

**Issue by nhan000** [sethyuan/logseq-plugin-tocgen#27]
Render Latex Code in TOC
![image](https://user-images.githubusercontent.com/85216095/163888942-5e716d73-89fc-4a78-a723-0856f50f0501.png)

**Comment by sethyuan** [comment]
I haven't worked with Latex before, I need some time to make some research.

**Comment by sethyuan** [comment]
Implemented, FYI.

**Comment by nhan000** [comment]
Works great! Thank you so much!

**Comment by nhan000** [comment]
Works great! Thank you so much!
