### ISSUE TITLE
Bug: PageJump not working in Logseq 0.6.6

### ISSUE THREAD

**Issue by AngeloChen14** [sethyuan/logseq-plugin-tocgen#28]
After upgrade Logseq to 0.6.6, the page button do not jump to the corresponding position anymore.

Platform: Logseq 0.6.6, Linux, tocgen v1.12.6

**Comment by AngeloChen14** [comment]
Issue is related to Dev theme, can't reproduce in default theme, close now.

**Comment by sethyuan** [comment]
I just ran a test on my local copy (macOS Logseq 0.6.6), it seems to work fine. Are all pages not working for you or just a few? I wonder if it's related to Logseq's lazy loading of pages.

**Comment by AngeloChen14** [comment]
> I just ran a test on my local copy (macOS Logseq 0.6.6), it seems to work fine. Are all pages not working for you or just a few? I wonder if it's related to Logseq's lazy loading of pages.

All pages are not working, the selected block is highlighted, but the page focus doesn't move. 
For now it only occurs on the Dev theme, I don't know if it's related to this plugin.

https://user-images.githubusercontent.com/45139524/164396597-82b08b4f-9bcc-45de-9c31-d21df39f6c48.mp4
