### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by myownstandard** [sethyuan/logseq-plugin-tocgen#3]
Logseq 0.5.6 Mac os.
I have installed plugin from Marketplace.
Than i have Inserted {{{toc [[pagename]]}}} into my page. And it is highlighting red and not generating any table of content..

**Comment by myownstandard** [comment]
<img width="778" alt="Снимок экрана 2021-12-31 в 17 16 22" src="https://user-images.githubusercontent.com/78643199/147827752-3945b00a-5396-4b97-b69f-f475e8e27f08.png">

**Comment by sethyuan** [comment]
Have you tried setting up macros? You can follow the instructions in README. You can also try to directly use `{{renderer :tocgen, [[pagename]]}}` to create TOC if you don't want to setup macros. Still, I'd recommend you to read README for more options.

**Comment by sethyuan** [comment]
Oh, I see you're using namespace. I tried it myself, the plugin does have an issue handling namespaced pages, I'll look into it and I'll let you know once I have it fixed.

**Comment by sethyuan** [comment]
@myownstandard I fixed the namespace issue and released a new version. You can give it try.

**Comment by sethyuan** [comment]
@myownstandard I released a new version providing a new slash command "Table of Contents", you use can it instead of macros, please check the usage demo in REAMDE.
