### ISSUE TITLE
无法显示三级及以上目录

### ISSUE THREAD

**Issue by zhuoqun-chen** [sethyuan/logseq-plugin-tocgen#32]
作者您好，我的目录页似乎有些问题，无论我输入几级目录，侧边目录始终只能显示两级，效果如下：

<img width="526" alt="Snipaste 2022_06_09_01_02" src="https://user-images.githubusercontent.com/73287160/172674902-217c46a1-08b3-43ca-9fe2-c3f72716a7b0.png">

我的插件配置为：

<img width="708" alt="Snipaste 2022_06_09_01_03" src="https://user-images.githubusercontent.com/73287160/172675010-7d188ee3-7c9a-41c6-ba37-66b475aba253.png">

请问是潜在的 bug 吗还是由于我的配置有问题？期待您的回答，感谢！

**Comment by zhuoqun-chen** [comment]
重启了两次软件，又重新建立了一次索引，突然可以正常显示了。

**Comment by sethyuan** [comment]
能用了就好，可能是数据的问题，重建索引就相当于重建Logseq内部的数据库。
