### ISSUE TITLE
Feature Request: Make Tags optionally visible in TOC items, from a toggle option in config settings

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-tocgen#33]
I have (imported) content using tags in headlines to be displayed as TOC entries to make them useful (tags are part of readable text)

For me modifying the local ``~/.logseq/plugins/logseq-tocgen/dist/index.****.js`` by commenting out the line containing the code from the source linked below works as workaround but will not survive updates.

````
content = content.replace(/(?:^|\s)#\S+/g, "")
````

Origin of code: https://github.com/sethyuan/logseq-plugin-tocgen/blob/master/src/utils.js#L25

I would be great to make the filtering of tags optionally to be disabled from the config.

**Comment by sethyuan** [comment]
Can you try to use the page reference syntax `[[]]` instead of tags `#`? tocgen was designed with the following facts in mind:

- Page reference is used when it's part of the content.
- Tag is used when an "extra" label for the content is needed.

That's why I left page references content intact while I removed tags from the TOC.

**Comment by acsr** [comment]
I completely agree with you, I have a customer delivering content to me, that rised that issue and I wanted to keep that in sync without change. Your excellent too helped me a lot to keep the overview on those external topics.

One of the challenges of mastering Logseq for people not aware of consequences of their markup is when their experience grows later. 

So creating on the fly transformations to clean up markup later are big helpers (for me) but also can create great damage.

To be honest or the TOC I had to prefix the corresponding lines with preceeding headline levels as well (aka #### etc.)
So for now forget the request, but it is a challenge to meet the restrictions to get a nice TOC anyway.

Since the TOC is not rendered on mobile and during export, I am rethinking the approach and trying to figure out to "hardrender" a copy of the TOC for Export and how to manage that. Logseq is still beta and there are lots of challenges and I **agree in not bloating options** resulting in dead ends later.
