### ISSUE TITLE
目录不显示标签，是否考虑增加

### ISSUE THREAD

**Issue by Sun-Pengcheng** [sethyuan/logseq-plugin-tocgen#34]
您好，对于block的首行里的标签，当前生成的目录中不显示，如用[[]]形式，则目录中可显示。能否在目录中显示标签呢？

虽然Logseq本身标签和页面是一样，但有时候习惯用标签格式，感觉更舒服。如果也能显示就更好了。

举例说明：如block首行包括[[abcd]]，则生成目录中显示abcd；如block首行包括#abcd，则生成目录中不显示。

**Comment by sethyuan** [comment]
这个不太符合tocgen的设计原则，tocgen的设计原则是标签用来做“额外”标记，正文采用页面引用。如果做支持的话会导致出现在TOC中的标题很乱。

**Comment by Sun-Pengcheng** [comment]
嗯，理解了，那我就用页面来标示好了，感谢回复~

**Comment by wandero** [comment]
@sethyuan 
同样的需求和问题，能否加一个设置项或开关，需要的自己打开标签支持呢
插件很好用，非常感谢

**Comment by sethyuan** [comment]
@wandero 我加了设置项，你更新下版本看看。

**Comment by wandero** [comment]
@sethyuan  ！！！再次感谢
