### ISSUE TITLE
可否增加一个展开几级目录的参数设置

### ISSUE THREAD

**Issue by gsgqgyq** [sethyuan/logseq-plugin-tocgen#35]
现在的插件相关设置有：默认展开、目录级数，能否增加一个展开几级目录的参数设置？例如：展开3级目录。这样3级以内的目录都是展开状态，更方便跳转一点

**Comment by sethyuan** [comment]
好主意，我尝试实现下。

**Comment by sethyuan** [comment]
@gsgqgyq 我发了新版本，实现了这个设置，用这个设置取代了之前的 `defaultCollapsed`。

**Comment by gsgqgyq** [comment]
那现在可否通过参数指定展示层级呢？就像这样：`{{renderer :tocgen, [[page name]], 1, h}}`

**Comment by sethyuan** [comment]
这个不能，展开几级是一个全局的设置。虽然也可以实现，但是我觉得没有必要每个TOC都有不同的默认展开级数，这样使用起来是不是太复杂了点。

**Comment by gsgqgyq** [comment]
我一开始的想法就是不同页面展开不同层级的目录，因为大纲格式有的时候层级真的太深了。你觉得复杂也是对的，现在这样就很好用了。
