### ISSUE TITLE
能否支持切换页面，自动刷新侧边栏的目录？

### ISSUE THREAD

**Issue by woden234** [sethyuan/logseq-plugin-tocgen#36]
我将toc用到了logseq 的目录上，写了{{renderer :tocgen,*,1}} 这个语法后，目录就随着页面修改而刷新。
但是切换页面后，需要关闭目录后重新打开，才能显示最新的页面内容。
所以能否支持切换页面自动刷新侧边目录的功能？
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/16451600/177288380-a3bae061-837f-4f0a-9ea0-611995530c77.png">

**Comment by sethyuan** [comment]
能确定一下你所使用的插件版本吗？我自己用最新的版本没有重现这个问题。

**Comment by woden234** [comment]
重新打开解决了，可以自动刷新了。谢谢
