### ISSUE TITLE
动态目录无法识别PDF高亮页的H1-Hn这种heading

### ISSUE THREAD

**Issue by Horinne** [sethyuan/logseq-plugin-tocgen#37]
习惯在阅读PDF时直接在PDF高亮页对高亮内容整理，但发现插件无法对此生效。

**Comment by sethyuan** [comment]
我测试了一下，是可以的呀。像这样 `## ((62cb7628-dcb6-4805-8a56-a6d62ce5fe79))`，是可以正常识别出来的。

**Comment by Horinne** [comment]
感谢回复，已解决问题，我自己的问题，所以我把Issue关闭啦
