### ISSUE TITLE
将所有的不同层级的标题都作为一级目录显示了出来

### ISSUE THREAD

**Issue by zqinmiao** [sethyuan/logseq-plugin-tocgen#38]
![image](https://user-images.githubusercontent.com/12278003/178144100-a4efa14e-a65a-428b-a316-3954f396867f.png)

如图，markdown中的一级标题：`SystemJS 不同的使用方法`、二级标题：`官方推荐以<script>标签的形式引入`，在左侧的目录树中都作为了一级目录显示。

预期：二级标题应当与一级标题为父子关系。

**Comment by sethyuan** [comment]
TOC Generator是依靠块层级而不是Markdown来生成大纲的，这匹配Logseq是一个Outliner的设计初衷，因此你说的这种用法是不被支持的。

**Comment by zqinmiao** [comment]
> TOC Generator是依靠块层级而不是Markdown来生成大纲的，这匹配Logseq是一个Outliner的设计初衷，因此你说的这种用法是不被支持的。

好的，明白了。谢谢

**Comment by alca7raz** [comment]
建议将这个问题加入Readme

**Comment by sethyuan** [comment]
> 建议将这个问题加入Readme

👌
