### ISSUE TITLE
TOC的展开和收起图标样式能够保持和 logseq 的一致吗

### ISSUE THREAD

**Issue by arpir** [sethyuan/logseq-plugin-tocgen#40]
logseq 的 UI 就有展开和收起的图标，看到TOC的与它不一致，浑身不舒服……
- 收起时，![5WHdj6](https://cdn.jsdelivr.net/gh/arpir/Pics@main/2022/08/13/5WHdj6.png)
- 展开时，![V5bHu1](https://cdn.jsdelivr.net/gh/arpir/Pics@main/2022/08/13/V5bHu1.png)

**Comment by arpir** [comment]
理解了，目录也是一个页面，它也存在层级。（也许那个下拉，展开的箭头没有必要，整体的样式保持与系统的一致就好了

**Comment by sethyuan** [comment]
我没看到有什么必要性，如果反馈的人多了再看看吧。
