### ISSUE TITLE
功能增强：字数显示限制 及 指定忽略某block

### ISSUE THREAD

**Issue by Gitbreast** [sethyuan/logseq-plugin-tocgen#41]
1. 有时某些块或子块内容比较长，且从逻辑上确实是跟同级的块并列的，不好再开一个块藏起来，这时如果toc涉及它的层级，就会显示一大段很长的话在目录中，影响观看，为了易于观看只能减少级数避免toc到它（有可能是第二层）。
改进提议：是否能在设置中添加一个填空，让用户设置硬性限制显示前N个字符，后面接一个省略号“……”表示未完，默认值为0即不限制显示字数。
2. 有时确实完全不想让某些块及其子块显示在toc中（各种原因：长度长、不从属于主逻辑却有关、重要性较次的备注等），通过将其它块改h1~h6来忽略个别的块及其子块实在麻烦。
改进提议：是否可以通过为个别块添加属性如 `toc:: false` 或添加tag如 `#tocfalse` 类似途径来忽略此块及其子块。

Plus. 一个次要的bug，高亮`==123==`和粗体`**123**`或斜体`*123*`同时出现如`==**123**==`或`*==123==*`时，toc中会显示`*`号如`**123**`。

**Comment by sethyuan** [comment]
嗯，应该是可以实现的，我看看有空加一下这两个功能。
另外提到的bug我也看一下。

**Comment by sethyuan** [comment]
关于 1 我又想了一下，设置字符数不是太好，因为中英文字符宽度不一样，而且英文不等宽字体字符与字符间宽度也不一样，也就是说同样100个字符，根据内容，有的情况下只有一行，有的情况下有两行。另外右侧边栏的宽度也不固定，你现在设置100个字符合适，宽度一变，又不合适了。

感觉还是得从内容本身着手，例如标题就不应该太长，长也只能认了。

**Comment by sethyuan** [comment]
2 和 bug 已经都弄好了，可以试试新版本。

**Comment by Gitbreast** [comment]
@sethyuan 感谢！2 的功能比较关键，更新已经可以使用了。1 这么说确实也有道理，个别情况我可以通过直接取字加省略号做一个父块，不想显示的情况下可以用 2 进行隐藏了。
