### ISSUE TITLE
目录支持增加章节数字序号

### ISSUE THREAD

**Issue by lzuliuyun** [sethyuan/logseq-plugin-tocgen#42]
首先非常感谢作者编写插件，可以自动生成目录，很方便的查看文档大纲内容。不过个人使用感觉有一点不习惯，看是否可以支持下。
1.   首先大纲能否支持展示章节数字序号，这样容易查看定位到具体的某个章节。比如：
<img width="166" alt="image" src="https://user-images.githubusercontent.com/6896562/190883384-e475e821-5273-4813-b24b-409cccc44ae9.png">

2.  其次每个标题带了一个“页面”字样，是否可以去掉呢？既然是大纲，就只展示标题就好了。不够这里似乎是其他插件的问题？
 <img width="252" alt="image" src="https://user-images.githubusercontent.com/6896562/190883279-b014dfdb-c176-498c-93c1-c83d23afc449.png">

**Comment by sethyuan** [comment]
1. 有空我可以加个设置看看，毕竟不是所有人都想要这个效果。
2. 那个“页面”是另一种跳转效果，如果你不想要的话可以通过设置里面的 `noPageJump` 去掉。

**Comment by sethyuan** [comment]
我在想加序号这个需求是否应该做在内容本身上，而不是TOC上。例如内容本身就维护了序号，那不是会和TOC生成的重复了？

另外加序号容易定位到章节的这个说法到底是不是成立的？有什么依据？如果是要定位当前光标所处位置在哪个章节的话目前插件已经实现了这个效果，所在章节层级都会高亮显示。
