### ISSUE TITLE
The 0 level expaneded by default do not work

### ISSUE THREAD

**Issue by mzwlevi** [sethyuan/logseq-plugin-tocgen#43]
<img width="696" alt="Screen Shot 2022-09-27 at 15 14 04" src="https://user-images.githubusercontent.com/78029539/192458867-74b02fdb-95b0-4760-8f39-20372f924283.png">
<img width="696" alt="Screen Shot 2022-09-27 at 15 14 40" src="https://user-images.githubusercontent.com/78029539/192458920-71f26078-75f5-4cf9-9444-2b52bf9e6ec1.png">

**Comment by sethyuan** [comment]
Good catch!

It is fixed now and a new version is released, please give it a try.
