### ISSUE TITLE
增加通过移动目录项目来移动关联的block的功能

### ISSUE THREAD

**Issue by ruanima** [sethyuan/logseq-plugin-tocgen#44]
![image](https://user-images.githubusercontent.com/14031394/193002157-5f62e88d-d877-46e1-852e-db16ea05d3d4.png)

为了便于对内容较多的页面进行整理，希望能通过移动目录项目来直接移动相关内容。
如图这个目录，如果把第二项移动到最前面，相应的也把对应的内容block移动到页面开头。

**Comment by sethyuan** [comment]
挺好的想法，我抽空实现一下。

**Comment by sethyuan** [comment]
我翻了一下我的笔记，发现我4月份的时候就想过这个功能，结果发现拖拽因Logseq上层的操作导致触发不了就放弃了。当时还在discord中反映过这个问题，没有下文。我再在discord里问下，看看Logseq能不能解决。

**Comment by ruanima** [comment]
> 我翻了一下我的笔记，发现我4月份的时候就想过这个功能，结果发现拖拽因Logseq上层的操作导致触发不了就放弃了。当时还在discord中反映过这个问题，没有下文。我再在discord里问下，看看Logseq能不能解决。

前端不咋熟悉，没想到限制这么多

**Comment by sethyuan** [comment]
好消息，拖拽已经实现了，可以用新版本尝试下看看。 @ruanima

**Comment by ruanima** [comment]
更新试用了，效果非常好o(￣▽￣)ｄ
