### ISSUE TITLE
【功能增强】右侧目录列表，点击页面，无法跳转到嵌入页面的相应位置

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-tocgen#45]
使用{{embed [[Project]]}} 在页面嵌入，右侧目录使用{{renderer :tocgen, *, 3}} ，点击页面按钮，无法跳转到嵌入页面的相应位置如果没法实现，希望点击页面按钮，能展开嵌入页面，显示所有内容

**Comment by sethyuan** [comment]
能否截个图来看看，我这边是可以的。

![image](https://user-images.githubusercontent.com/3410293/194808472-8d3c1c20-dc7f-4ec3-ae5d-d5fb1cea04fa.png)

目前点嵌入页的“页面”会带你到它第一个块的位置。另外一般点”页面“不起作用是内容的延迟加载导致的，可以检查下这种情况，如果是这种情况则需要先滚动下页面，将要定位到的内容加载出来。

**Comment by aiyou9** [comment]
我这里是没有展开引用快，导致无法跳转的，确实跳转块，聚焦更好，多谢！！！
