### ISSUE TITLE
Is there anyway to have the menu unfolded?

### ISSUE THREAD

**Issue by drawingthesun** [sethyuan/logseq-plugin-tocgen#47]
I have a page where I generated 4 levels of TOC and that works very well, but I have to click the arrows and unfold each menu item.

Is there a way to ensure all levels are unfolded?

Edit: I know there is a default option, I want a way to by pass that, so on a menu by menu basis.

**Comment by sethyuan** [comment]
What if I provide two buttons? "Collapse All" and "Expand All" for each TOC.

**Comment by drawingthesun** [comment]
Yeah that would awesome thank you!

**Comment by sethyuan** [comment]
@drawingthesun It's implemented, please check the new version.
