### ISSUE TITLE
logseq 0.8.8 插件不工作

### ISSUE THREAD

**Issue by FloatingGuy** [sethyuan/logseq-plugin-tocgen#48]
插件版本：1.20

测试：
{{renderer :tocgen}}

**Comment by sethyuan** [comment]
能给个具体的示例吗？我这边看到都是好的。

**Comment by FloatingGuy** [comment]
> 能给个具体的示例吗？我这边看到都是好的。

<img width="455" alt="Snipaste_2022-10-18_10-27-51" src="https://user-images.githubusercontent.com/6472909/196321248-2c027d8e-ec0f-45bb-b17c-d288d0caf06d.png">

**Comment by sethyuan** [comment]
你是怎么安装的插件呢？是通过插件市场吗？方便的话可以按 `cmd+opt+i` 或者 `ctrl+shift+i` 打开console，再输入一下TOC看看具体是什么错。

**Comment by FloatingGuy** [comment]
> 你是怎么安装的插件呢？是通过插件市场吗？方便的话可以按 `cmd+opt+i` 或者 `ctrl+shift+i` 打开console，再输入一下TOC看看具体是什么错。

我是手动下载 release 安装包，替换plugins 目录下的插件目录。
<img width="850" alt="Snipaste_2022-10-18_13-14-20" src="https://user-images.githubusercontent.com/6472909/196341709-af23d24c-3c2c-44bd-a595-14af851c6646.png">
<img width="1088" alt="Snipaste_2022-10-18_13-17-21" src="https://user-images.githubusercontent.com/6472909/196341739-c6a6b990-e3e3-4441-9d73-a110cc1921c9.png">

**Comment by sethyuan** [comment]
看起来就是这个原因导致的。建议使用插件市场安装，或者你可以尝试开开发者模式，然后在插件页加载插件。

![image](https://user-images.githubusercontent.com/3410293/196342665-34592d7d-1315-4a7c-aad3-d8c481bdf678.png)

**Comment by FloatingGuy** [comment]
🙏感谢， 问题解决。
