### ISSUE TITLE
Plugin not working when using namespace

### ISSUE THREAD

**Issue by zllx666** [sethyuan/logseq-plugin-tocgen#5]
Logseq 0.5.6 
tocgen 1.3
When Inserted command {{{toc [[pagename]]}}} into my page. The command disappear and not generating any table of content.
This happens when the page has 3 levels, the plugin works good if the page only has 2 levels.

e.g., I have 3 pages [[AA/BB/CC]], I can generate TOC for page BB using command {{{toc [[AA/BB]] }}}, but I cannot generate TOC for page CC using command {{{toc [[AA/BB/CC]] }}}.

**Comment by sethyuan** [comment]
It should be fixe now, please upgrade the plugin and give it a try.

**Comment by zllx666** [comment]
It's working now, thanks for the awesome plugin.

**Comment by sethyuan** [comment]
Glad you like it! 😃
