### ISSUE TITLE
您好，请问生成的目录块内部有可能识别特定的标题实现单行加粗吗？

### ISSUE THREAD

**Issue by silvericbin** [sethyuan/logseq-plugin-tocgen#50]

**Comment by sethyuan** [comment]
有具体使用场景吗？为什么要单行加粗呢？

**Comment by silvericbin** [comment]
可能是我在做笔记的时候做的层级有些多，有的时候会漏掉一些嵌套，所以主要用#标题作为分级，于是目录都是平行的，看的时候没有字体的变化会有一点不清晰；我自己将目录的标题加粗了，所以就想咨询一下目录的正文是否能够选择性加粗，如果目前实现不了也没关系！是我个人的咨询！谢谢您！

**Comment by sethyuan** [comment]
你可以结合#标题与缩进来做目录。例如下面内容：

```
- # 标题1  
	- ## 标题2  
		- ### 标题3  
- # 标题1  
	- ## 标题2  
```

插件配置里设置为`h`的话就是只看#标题：

![image](https://user-images.githubusercontent.com/3410293/205317244-e46af6f0-34c1-408a-832d-9bd53ccd4df8.png)
