### ISSUE TITLE
Hidden feature (or bug) discovered: Moving blocks in TOC hierarchy moves block in original position permanently

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-tocgen#51]
Today I dragged and dropped by accident a TOC item in a TOC that referenced just a particular block on the page only.

Form: 
`{{renderer :tocgen, ((63988e4a-6886-4ccd-ad6f-c4232c4775ce)), 2}}
`
### Behaviour detected 

- I moved a level 2 subitem from inside toplevel last item into mid of first item.q
- When checking the original block the block was relocated toi the position in hierarchy the dragged item now resides in the TOC.
- Moving the item back to its origin via TOC also worked.

I did not scan the changelogs or code comments to find it mentioned there.

### Nice Part

This feature is not mentioned in the docs but quite useable to restructure large outlines while keeping a birds eye view without collapsing the actual blocks first.

### Pitfalls

- Because it is not a documented feature, no one cares and it might vanish by accident
- Because it is not documented it can cause a serious mess if do not recognise such a change and miss to immediately undo it.

### Suggestion

Reproduce if I am right and include it in the docs!

I love your plugin!

**Comment by sethyuan** [comment]
Hi @acsr , thanks for the report. This feature is indeed already documented in README, maybe not in a very prominent way.

![image](https://user-images.githubusercontent.com/3410293/207476855-1822981f-c620-466b-a6b1-01673579fae1.png)

I'm glad you find it useful. Depending where you're dropping the item, you can place the block "before", "after" or "inside of" another block.
