### ISSUE TITLE
功能需求：目录栏跟随滚动

### ISSUE THREAD

**Issue by hongshuo-wang** [sethyuan/logseq-plugin-tocgen#52]
举例说明：
正文滚动到了标题为4.6的位置，但是目录到3就到底了，没有跟随移动到4.6
希望可以增加功能实现正文滚动到哪里，目录就跟随显示到哪里
![image](https://user-images.githubusercontent.com/66150472/212771020-19017df0-221a-476f-8c5f-2643528a140e.png)
此外，这是我的插件设置
![image](https://user-images.githubusercontent.com/66150472/212771266-5863e29f-4570-45b1-8dc1-d22426de2106.png)

**Comment by sethyuan** [comment]
滚动会带来一个问题，就是侧边栏的不稳定性，因为侧边栏里其实并不只有TOC，还可能会有其它的内容或块，如果来回滚动的话会非常影响使用体验。

针对你的需求我想了一下，也许可以添加有限制的滚动，例如我可以尝试给TOC增加一个高度参数，给了高度的TOC就可以在内部稳定进行滚动了。我尝试一下。

**Comment by hongshuo-wang** [comment]
https://github.com/mschmidtkorth/logseq-msk-toc
之前我在寻找类似插件时发现上面这个项目可以将目录悬浮起来显示，是不是logseq已经支持这类功能了呢，如果有的话是否可以将toc也悬浮起来以解决滚动带来的不稳定性

**Comment by sethyuan** [comment]
“悬浮”是可以做的，但是我个人不偏向这种使用方式，因为总会有部分窗口内容被遮挡，不如侧边栏好用。

关于功能本身，我已经实现了通过给动态目录一个高度来支持稳定的随主内容滚动的效果。试试新版本。你需要将之前的 `{{renderer :tocgen, *}}` 改为 `{{renderer :tocgen2, *, 300px}}`。300px是高度，你可以设置一个适合自己的高度。

**Comment by hongshuo-wang** [comment]
完美解决了！感谢
