### ISSUE TITLE
Suggestion: Separating languages of README, donations

### ISSUE THREAD

**Issue by candideu** [sethyuan/logseq-plugin-tocgen#54]
Thank you for creating this app!

I just had a suggestion for the README: Alternating between both languages makes things difficult to understand for those of us who only understand one of the languages, and makes it difficult for screen readers and text-to-speech software. I would suggest either doing one language, and then the other language, or having separate README files for each language, and linking both to each other.

Additionally, do you have a tip jar for people to support your work?

**Comment by sethyuan** [comment]
Yeah, it feels messy to me too. I separated the README as you suggested.
I don't have a donation setup yet, too lazy to put effort on that right now, but thanks for asking.

**Comment by candideu** [comment]
Sweet, thank you!
