### ISSUE TITLE
Support for nested headings

### ISSUE THREAD

**Issue by candideu** [sethyuan/logseq-plugin-tocgen#55]
Hi @sethyuan! Would it be possible to add the option of displaying nested headings as well? Right now, any subheading nested under another doesn't display.

![image](https://user-images.githubusercontent.com/55474996/216369209-c664827e-4a29-410e-ba0f-3c8f4c3287a3.png)

For comparison, [logseq-toc-plugin](https://github.com/hkgnp/logseq-toc-plugin) displays subheadings underneath higher level headings.

![image](https://user-images.githubusercontent.com/55474996/216371289-f4e4c9dd-64ef-40c1-b351-3c3c28cae5ed.png)

**Comment by sethyuan** [comment]
It's definitely supported, the culprit here is the default setting. The default value is to just generate 1 level of TOC, you can change it in the plugin's settings. I also decided to change the default value as it may introduce confusions, I'll release a new version later.

**Comment by sethyuan** [comment]
New version is released. It also features creation of TOC via page's context menu, it is the new recommended way to use the plugin.

**Comment by candideu** [comment]
> New version is released. It also features creation of TOC via page's context menu, it is the new recommended way to use the plugin.

Works great, thanks for the update!

**Comment by Antiwhore** [comment]
Hello!
No, it doesn't work. I tried setting both default levels and even expansion levels, but as soon as I indent a header, it vanishes from the TOC.

**Comment by candideu** [comment]
@

> Hello! No, it doesn't work. I tried setting both default levels and even expansion levels, but as soon as I indent a header, it vanishes from the TOC.

I'm not seeing this issue, unfortunately... Nested headings appear when I toggle the arrow:

![image](https://user-images.githubusercontent.com/55474996/220236655-839e1c39-1495-4928-9921-a69753ed4c67.png)

I'm running v2.2.5. Here are my settings:

![image](https://user-images.githubusercontent.com/55474996/220237009-06fe2dfa-b95e-4470-8ebe-9f7dfdd4c391.png)
