### ISSUE TITLE
A tag with space (`#[[...]]`) is not handled correctly

### ISSUE THREAD

**Issue by trustin** [sethyuan/logseq-plugin-tocgen#56]
:wave: The following block:

```
# 2023-01-01 #[[Meeting note]]
```

is displayed as:

```
2023-01-01 note]]
```

It looks like the plugin strips the tag with spaces incorrectly.

**Comment by sethyuan** [comment]
Thanks for reporting, an update with the fix is released.

**Comment by trustin** [comment]
That was super quick. Thank you very much! 🙇
