### ISSUE TITLE
0.8.16nightly版本点击无反应

### ISSUE THREAD

**Issue by gujin03** [sethyuan/logseq-plugin-tocgen#57]
![iShot_2023-02-07_21 46 07](https://user-images.githubusercontent.com/38389059/217262519-fe8c30ad-c31d-4738-ab4c-bf015bdfcd34.gif)
录屏如上，请作者检查，谢谢

**Comment by sethyuan** [comment]
TOC Generator默认使用markdown的标题语法`#`作为大纲的识别，录屏上的页面中貌似没有标题，所以目录是空的。
