### ISSUE TITLE
Indented headings not included into TOC

### ISSUE THREAD

**Issue by Antiwhore** [sethyuan/logseq-plugin-tocgen#58]
Hello!
No, it doesn't work. I tried setting both default levels and even expansion levels, but as soon as I indent a header, it vanishes from the TOC.

_Originally posted by @Antiwhore in https://github.com/sethyuan/logseq-plugin-tocgen/issues/55#issuecomment-1431978219_

**Comment by sethyuan** [comment]
TOC is generated based on block levels, not markdown's `#` number. This is mentioned in README already.

**Comment by sethyuan** [comment]
Can you upload some screenshots so we can take a look of you use case?

**Comment by Antiwhore** [comment]
What do you want to see on the screenshots? The TOC?

**Comment by sethyuan** [comment]
The TOC and the page the TOC refers to.

**Comment by Antiwhore** [comment]
I can give you the screenshots, but they won't show anything besides what I've explained.
Here's a fragment of TOC for a page:
![TOC](https://user-images.githubusercontent.com/121800962/219350620-90f1ed75-26ed-4de8-bc20-bd58da010195.png)
And here's a fragment of the page itself:
![Headings](https://user-images.githubusercontent.com/121800962/219350738-2e6cf79b-37af-4a7a-9d66-76cd19910906.png)
As you can see, only the top level heading is included, while the indented ones are missing.

**Comment by sethyuan** [comment]
OK, I see the problem here. You have heading blocks under non-heading blocks, that's why they're not recognized as headings in TOC.

**Comment by Antiwhore** [comment]
And why in the world do they have to be under other headings? That's a senseless limitation that mustn't be there at all. You must fix it.

**Comment by sethyuan** [comment]
@Antiwhore You're welcome to submit PRs.

**Comment by Antiwhore** [comment]
First, I would submit PRs if I was a developer of this plugin, which I'm not.
Second, there must be no need for PRs at all, because it must have been done this way from the beginning.
And third, where in the description is a mention that it doesn't work in this case? Nowhere. Ergo you're a swindler, cause you're promoting a defective tool as a working one.
