### ISSUE TITLE
Does not produce any output

### ISSUE THREAD

**Issue by antonba** [sethyuan/logseq-plugin-tocgen#60]
It correctly identifies the page, but does not produce any output, regardless of settings or level of complexity of the page.

![image](https://user-images.githubusercontent.com/1065579/222550788-211b2008-bae7-41ca-b941-5721cf1272be.png)

![image](https://user-images.githubusercontent.com/1065579/222550841-ea25c6c0-6f0a-49c2-9eea-7699a37d2a8b.png)

Tried

{{renderer :tocgen2, *}}
{{renderer :tocgen2, *, auto, 3}}

Also calling the plugin from within the page (rather than from the Contents page) does not work either (produces same empty output). Any suggestions as to what might be going wrong?

**Comment by sethyuan** [comment]
@antonba By default, only headings are used to construct the table of contents. You can add headings by using markdown (# syntax) or via the block's context menu. You can also change the default setting to `any` to use all blocks, not just the heading ones, to construct the TOC.

![image](https://user-images.githubusercontent.com/3410293/222601336-0453598d-ad58-45b4-ba7b-95cfbe74b131.png)

**Comment by antonba** [comment]
Thanks for the prompt response and sorry for missing this (the last code sample did talk about headings). Although, speaking of the plugin settings, I discovered they even exist only after your response here. Might be useful to have the readme describe what settings exist if only to raise their visibility. Great work, otherwise! :)
