### ISSUE TITLE
[Feature request] Render todo/done as checkboxes

### ISSUE THREAD

**Issue by Bad3r** [sethyuan/logseq-plugin-tocgen#61]
Hey there!
The last update has been great to work with.
I use TODO/DONE to keep track of where I last stopped in a large document.
For example, I have pages where each block covers a topic. Once I am done with the block, I mark the header as done.
![image](https://user-images.githubusercontent.com/25513724/225207743-4b4439de-6409-4a1f-bac8-987be7f33c9e.png)

Would it be possible to not display the text `TODO`/`DONE` and replace it with the checkbox only?

**Comment by sethyuan** [comment]
How about this?

![image](https://user-images.githubusercontent.com/3410293/225214402-89491a44-78c1-4cb1-8177-0a296a82b11f.png)

**Comment by Bad3r** [comment]
@sethyuan perfect :bowing_man:

**Comment by Bad3r** [comment]
Could the title be greyed out for done tasks? that will make it easier to differentiate while skimming

**Comment by sethyuan** [comment]
Implemented. You can further customize the style with this CSS class: `.kef-tocgen-done`

**Comment by Bad3r** [comment]
Just tested it & it works perfectly. Thank you for the quick implementation :D
