### ISSUE TITLE
[Suggestion] use icon instead of `page`

### ISSUE THREAD

**Issue by Bad3r** [sethyuan/logseq-plugin-tocgen#62]
hey there again :D 
what do you think about swapping `page` link with an icon from Tabler font.
![image](https://user-images.githubusercontent.com/25513724/225347621-323de71f-6365-437d-8ef8-deaaa3808250.png)

Icon suggestions:
![image](https://user-images.githubusercontent.com/25513724/225347869-00dab754-84c0-4a16-b549-707f2d77f6d5.png)
![image](https://user-images.githubusercontent.com/25513724/225349599-68371459-5c55-487b-b471-1afab3824bd7.png)
![image](https://user-images.githubusercontent.com/25513724/225349762-c7ee728e-b632-4681-a227-9f5e4ae75d15.png)
![image](https://user-images.githubusercontent.com/25513724/225347940-e6350725-9947-4ef4-a0a7-75b7baad30c9.png)
![image](https://user-images.githubusercontent.com/25513724/225348657-d95503ba-af7c-41df-b191-4ca4e572e334.png)
![image](https://user-images.githubusercontent.com/25513724/225349387-e7ebe4f7-e9e0-4b7b-9d0d-bfc5c05de2b6.png)
![image](https://user-images.githubusercontent.com/25513724/225349871-60ac2333-ed94-43b5-9599-639514cb6b13.png)

https://tablericons.com/

**Comment by sethyuan** [comment]
How about this one, I think it better represents "go to".
<img width="137" alt="image" src="https://user-images.githubusercontent.com/3410293/225486332-f723956f-8915-4734-9f16-594de1786d64.png">

**Comment by sethyuan** [comment]
Implemented.

**Comment by Bad3r** [comment]
Great Tha k you!

**Comment by Bad3r** [comment]
hey, did some testing and the icon does not load. I have tested in a clean VM with a new Logseq installation to confirm.
![image](https://user-images.githubusercontent.com/25513724/226701070-077ac88e-57fd-46bc-b356-6eac30f68a6c.png)

Is the icon from Tabular font?

**Comment by Bad3r** [comment]
if the icon is from tabular font 2.0 it wont work in Logseq. Only <1.99

**Comment by sethyuan** [comment]
My bad, used a font from a theme. 😅 I just fixed it, please try again.

**Comment by Bad3r** [comment]
Thank you! just tested and can confirm its working as expected.
