### ISSUE TITLE
Feature Request: Make TOC initially collapsed (to a certain level) and allow Alt-Click to expand all childs

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-tocgen#63]
In very long documents with need for more nested levels, the sidebar TOC is not a suitable UI.

On the other hand on initial visit of a page you might dive not dive into deeper levels at once and only need to unfold the TOC after selecting a certain chapter of interest.

You can globally set the default levels and per instance, and you can collapse the TOC later.

My usual Workaround is to place a depth 1 TOC at the top as overview and a deeper one below.
This one is the favorite candidate for an initially collapsed TOC.

Alt-Click
To fully collapse or expand all childs of a node using Alt-Click does not work with the Logseq blocks folding as well. 
This pattern is a basic concept in macOS nested lists e.g. folder listings in Finder.

**Comment by sethyuan** [comment]
- There is a plugin setting that controls the default expansion level (it's not per instance).
   
![image](https://user-images.githubusercontent.com/3410293/226504313-7e0575ec-0886-4441-b297-cfc11e8cba96.png)

> fully collapse or expand all children

This I can implement, but it may take some time, since I have other priorities.

**Comment by acsr** [comment]
Thx for the quick response. I will try that option first and report if this suits my needs. No idea why I have overseen this. I maybe confused this with default_depth and the 999 made me blind for it.

As you say this is global and would be nice per instance of TOC.

For the fully collapsed challenge I now put a wrapper Block around the TOC and collapse this one. The cumbersome thing is that you have to reset the state of the wrapper block after every use. In general this would be useful for Logseq to have the choice beteen a permanent collapse and or an expand until next open. And even that can be  managed by changing the personal habit, because collapsed blocks are expanded if opened in isolation.

**Comment by acsr** [comment]
cool even defaultExpansionLevel = 0 works for initially fully collapsed TOCs. Need to check the effect on export as HTML/PDF

**Comment by sethyuan** [comment]
"alt click the arrow to expand/collapse all descendants" is implemented. @acsr

**Comment by acsr** [comment]
@sethyuan Just found it. Great, you are awesome!
