### ISSUE TITLE
Other TOCs in the Contents pane

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#65]
When I am working on a Page, I use the ToC, however I do not want to see the TOCs of other Pages.
Is there a way to hide those, or, better still, prevent them from being shown too? I only want to see the TOC for the Page I am editing.

**Comment by sethyuan** [comment]
You can close it after usage:
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/3410293/6e0dbdce-e220-42f5-b183-07c1892b38d7)

Or, you can create a dynamic TOC in the right sidebar, this will change content according to the main page you're working with at the moment. The scenario 1 gif demonstrates the use of dynamic TOCs.

**Comment by DutchPete** [comment]
Yep, the dynamic toc is my buddy. Thank you.
