### ISSUE TITLE
jump to later sections in longform notes

### ISSUE THREAD

**Issue by chs33** [sethyuan/logseq-plugin-tocgen#66]
As far as I observe, due to Logseq's lazy loading for longform notes, click on the section that are not loaded yet won't jump you to that section, my workaround is to scroll down to the bottom of the page let it load everything and then it is good. I am wondering is it possible to improve on this? After all, the whole point of table of content is to being able to jump arbitrarily on real longform notes.

**Comment by sethyuan** [comment]
It's a long-standing issue, theoretically speaking, it should be solved by the Logseq plugin SDK, there is little the plugin can do.

Anyway, I'll keep making researches about this, will let you know once I have new findings.

**Comment by sethyuan** [comment]
@chs33 I implemented an algorithm to try hard to handle the lazy loading. Please have a try.

**Comment by arigit** [comment]
Hi @sethyuan , landed here as I am new to logseq, I migrated some VERY long pages to it and I am using to ToC plugin extensively (it's awesome, thanks). 
The way you are working around lazy loading works well for medium-sized pages of up to some 10 "screens" long, but on longer pages, it seems to time out and stops jumping down. I figure that you have set some maximum time out value after which you stop "paging down", could you allow your workaround to try longer (at least 3X the time you try today)? - or if this impacts other things, make the timeout / max page-down configurable?

**Comment by sethyuan** [comment]
@arigit  Sure, I can add a plugin setting for the number of times to try to scroll down.

**Comment by sethyuan** [comment]
@arigit The setting is added.

**Comment by arigit** [comment]
Just tested it and it works great. I had to increase the default max number of scroll-downs to 35. Thanks a zillion for this
