### ISSUE TITLE
[FEATURE REQUEST] add auto-numbering

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#67]
I am reading a book and simultaneously highlighting with the PDF viewer. I nest my blocks under headings and subheadings. But when the page becomes long with many headings, it is easy to get the indentations and heading levels (the number of `#`) out of kilter, which means that the ToC, like me 😀, gets confused and leaves headings out.

To correct that, I keep having to count the indentation levels and the heading hashes to make sure they match. It would be useful to have automatic heading numbering, that way you don't have to count. Note: the numbers should not be embedded in the note, they should be more like an overlay.

In Obsidian there is a plug-in that deals with it, perhaps it could help in modifying it for Logseq.
[obsidian-heading-count-plugin.zip](https://github.com/sethyuan/logseq-plugin-tocgen/files/11689716/obsidian-heading-count-plugin.zip)

**Comment by sethyuan** [comment]
I believe what you want is the "auto heading" feature in Logseq.

In the block's context menu, choose "auto heading":

<img width="285" alt="image" src="https://github.com/sethyuan/logseq-plugin-tocgen/assets/3410293/d2e0750b-a4e4-4f31-9db2-219ad012dadc">

This is how it looks like with "Woz theme":

<img width="288" alt="image" src="https://github.com/sethyuan/logseq-plugin-tocgen/assets/3410293/384cc445-95ef-4574-9f20-427dfc842c24">

In case you have the "Another Embed" plugin (my other plugin) installed, it has a customizable shortcut key that you can use to toggle the auto heading.

**Comment by DutchPete** [comment]
Thanks for the suggestion, but that is not what I am after. I am after auto-numbering.
Like this:

## 2. Header title
    ### 2.1. Subheader title
        #### 2.1.1. Sub-subheader title
## 3. Another header title
etc.

Auto-heading could used in an ancillary function to make visible which heading is used. So in my example above the `3. Another header title` could lead one to believe it is an H3 heading, when in fact it is an H2 ➙ auto-heading can help.

**Comment by sethyuan** [comment]
I see. I have another plugin that does numbered lists, https://github.com/sethyuan/logseq-plugin-ol

With it, you can achieve something like this:

![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/3410293/3ddee35d-fab6-4f05-a77e-f00236ed5d58)

But as you can see, currently it's not aligned to the heading's font style. This can be solved by a newer version of Logseq later (when it updates its Electron version).

**Comment by DutchPete** [comment]
I only want the headings to be numbered, not the blocks nested below them. Can the plug-in do that? If so, how do I do it?

**Comment by sethyuan** [comment]
Oh, I'm afraid it's not possible.

**Comment by DutchPete** [comment]
Yep, that's what I thought. Thanks for your suggestions anyway.

**Comment by sethyuan** [comment]
Maybe I can create another plugin especially to deal with this.

**Comment by DutchPete** [comment]
TBH, I don’t know if it is worth your while. I say that because I wonder if any other people have raised this issue with you. Sometimes though, you don’t know you need something, or don’ realize how your workflow could be improved a bit by a new thing. Perhaps it is worth waiting to see if others show an interest?
