### ISSUE TITLE
生成的 TOC 没有层级缩进效果

### ISSUE THREAD

**Issue by kevinfszu** [sethyuan/logseq-plugin-tocgen#69]
系统： Win 10
Logseq 版本：0.9.9

实际效果：（没有安装任何 theme，同时移除了所有 custom.css 样式，都没办法得到期望中的缩进效果）
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/5536550/268725a6-0fcf-4014-a0cf-d5f959c3e4c3)

期望的效果：
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/5536550/99d96a7b-e759-458f-9f80-29c20680723e)

**Comment by sethyuan** [comment]
tocgen是根据缩进级别来识别大纲的，在README中有说明哈 。

**Comment by canxer314** [comment]
> tocgen是根据缩进级别来识别大纲的，在README中有说明哈 。

看了半天README也没地方提到有缩进级别的
