### ISSUE TITLE
[SOLVED] Page/Block not found!

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#70]
I had an H2 header, which I subsequently deleted. There is no open space on the page, yet in the ToC `[Page/Block not found!]` is shown in red above the title of the page.

I tried reindexing but the message remains.

**Comment by sethyuan** [comment]
You probably have a TOC pointing to an non-existent entry (page or block). You can edit the TOC block to check it.

**Comment by DutchPete** [comment]
What I have on the page is:

Contents
- [Page/Block not found!]
- {{renderer :tocgen2, [[existing page]], calc(100vh - 134px)}}

**Comment by sethyuan** [comment]
Because it is a standalone block, if you don't want it you can delete it.

**Comment by DutchPete** [comment]
Oh, i did not know that is possible, I thought no changes could be made in the sidebar. Anyway, I deleted it.
