### ISSUE TITLE
Allow setting `h` or `any` on a per-TOC basis

### ISSUE THREAD

**Issue by rben01** [sethyuan/logseq-plugin-tocgen#71]
Currently you must choose `h` or `any` for the whole plugin, and that setting is applied to all tables of content, workspace-wide.

It would be great to be able to override the plugin setting and write something like `{{renderer :tocgen2-any, *}}` to get a TOC that uses the `any` setting. The result would be:

- `{{renderer :tocgen2, *}}` uses plugin setting
- `{{renderer :tocgen2-h, *}}` always makes a TOC based on headers
- `{{renderer :tocgen2-any, *}}` always makes a TOC based on all blocks

**Comment by sethyuan** [comment]
This is already possible, please read the README.
