### ISSUE TITLE
[FEATURE REQUEST] Automatic ToC update with page change

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#73]
Currently, a ToC is temporary: you click on the icon and a ToC is generated in the right-hand sidepanel. However, if one changes to a new page, the original ToC is still there, and clicking on the ToC icon creates a new one below the original one. The latter has become obsolete and needs to be deleted, unless one returns to the original page soon afterwards.

This system is laborious with having to click to create and click to delete.

Would it be possible to have a ToC be created automatically for a page and have it replace the ToC of a previous page? I imagine something like the ToC macro referring to whichever page is open in the central pane, thus updating automatically upon page change.

**Comment by sethyuan** [comment]
Hi @DutchPete , such "dynamic" ToC is already existent, look at the README, where the "Scenario 1" demo video shows how to use it.

https://github.com/sethyuan/logseq-plugin-tocgen/blob/master/README.en.md

**Comment by DutchPete** [comment]
Thanks for your quick reply, @sethyuan.
I am already using the dynamic ToC, but it is not what I mean with this FR.

In Scenario 1 the ToC changes with changes made to the page - let's call it Page 1. However, if you replace Page 1 with another page, let's say Page 3, then the ToC does not change to show the headers of Page 2.

**Comment by sethyuan** [comment]
OK, got it. Correct me if I'm wrong, what you want is that every time I click on the toolbar button to open a ToC, the previous opened ToC gets replaced with the new one, right?

I'll follow this up when I get some spare time.

**Comment by DutchPete** [comment]
> every time I click on the toolbar button to open a ToC, the previous opened ToC gets replaced with the new one

That is right.

But what I am really wondering is if it is not possible to do away with the clicking altogether by including in this macro `{{renderer :tocgen2, [[page]], calc(100vh - 135px)}}` a reference to the current page in the central pane.

That way, I could just click the ToC toolbar button only once, and each time I change the page in the central pane the ToC changes with it. Now, that would greatly benefit the workflow.

BTW, I understand you do this in your spare time so there is no pressure from my side to get this done; I am grateful for your fantastic plug-ins - I wish I could make a contribution with Bitcoin but I know you cannot accept.

**Comment by sethyuan** [comment]
> That way, I could just click the ToC toolbar button only once, and each time I change the page in the central pane the ToC changes with it. Now, that would greatly benefit the workflow.

Then you just need to replace `[[page]]` with `*`, making it a dynamic ToC.

`{{renderer :tocgen2, *, calc(100vh - 135px)}}`

**Comment by DutchPete** [comment]
Yep, that is exactly what I meant. Many thanks!

**Comment by sethyuan** [comment]
@DutchPete Yeah, you're right. I don't know what was I thinking when I made the demo. 😂
