### ISSUE TITLE
Hooked arrow does not work properly

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#74]
I am on macOS and am using the latest Tocgen plug-in, of which I use the dynamic ToC in the right-hand panel.

When, after launching Logseq, I click on a hooked arrow, it will take me to the section on the page. When I thereafter click on another arrow, it does not do anything.

Sometimes when I click on the hook it brief jumps to the section but then jumps right back to the top of the page.

**Comment by sethyuan** [comment]
I just ran a test with own and it worked OK, could it be that you have some other plugin that's moving the page's position?

**Comment by DutchPete** [comment]
These are the plug-ins I use. I you don't see one that strikes you as risky then it is something else on my side I will have to scout for.

![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/10794265/5256dbd9-658f-45ef-93ee-117a8e799cde)
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/10794265/992a289d-8da5-451a-a202-d467e4b0ceb1)

**Comment by DutchPete** [comment]
I think I have found the culprit: _Save Scrollbar Position_.
Disabling made the ToC in the right-hand pane behave as expected.
