### ISSUE TITLE
Table of Contents is not correctly displayed when there is space in page title

### ISSUE THREAD

**Issue by HaomingFu** [sethyuan/logseq-plugin-tocgen#76]
# Issue
Table of Contents is not correctly displayed when there is a space in page title.

# Repro
1. Create a new page
2. Create the following 4 blocks on the said new page
```
[nono]([[page1]])
[noyes]([[page 2]])
[yes no]([[page3]])
[yes yes]([[page 4]])
```
3. Click "open-toc" button to create a table of contents on the right pane.
4. The table of contents looks like the following:
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/7111769/72a6bc23-b915-4f7f-8dac-64aef3657e41)

# Expected Behavior:
When you type in the said 4 blocks on a page, and then generate a table of contents for it, I expect the table to look like:
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/7111769/643e5014-e149-4a7e-9e5c-2a65c2030b9a)

Which is to say, within the table of contents, "[noyes](page 2)" is changed to "noyes", and "[yes yes](page 4)" "yes yes".

# My Thoughts
- The table items "[noyes](page 2)" and [yes yes](page 4)" do not look right because there is a space in the page title, i.e., there is a space in strings "page 2" and "page 4".
- There is no space in page titles "page1" and "page3", so their corresponding table items display in a right way.
- It does not affect the table items no matter whether there is a space in the string enclosed by square brackets, i.e., "nono", "noyes", "yes no" and "yes yes".

**Comment by sethyuan** [comment]
Fixed.
