### ISSUE TITLE
Table of Contents is not correctly displayed when a block is referenced

### ISSUE THREAD

**Issue by HaomingFu** [sethyuan/logseq-plugin-tocgen#77]
# Issue
Table of Contents is not correctly displayed when a block is referenced.

# Repro
1. Copy the reference of an existing block, which in my case is ((6575291d-06af-4150-af9e-6508dade1746)).
2. Create a new block using the said block reference like the following:
```
[new block](((6575291d-06af-4150-af9e-6508dade1746)))
```
3. Click "open-toc" button to create a table of contents on the right pane.
4. The table of contents looks like the following:
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/7111769/b042c0f0-d729-4930-9b9a-9118f75c7870)

# Expected Behavior:
When you create a new block using some block reference, and then generate a table of contents for it, I expect the table to look like:
![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/7111769/d0477739-dcb4-46e0-927d-89e224575c67)
That is to say, the table item "new block))" is changed to "new block".

**Comment by sethyuan** [comment]
Fixed it.
