### ISSUE TITLE
[Feature Request] Collapse the whole TOC

### ISSUE THREAD

**Issue by JJAYCHEN1e** [sethyuan/logseq-plugin-tocgen#9]
Since I'm getting a longer page, the TOC in the right sidebar is also going to be much longer. It would be nice if the TOC itself can be collapsed.

**Comment by sethyuan** [comment]
Fair enough, I'll look into it tomorrow, it's a bit late now.

**Comment by sethyuan** [comment]
@JJAYCHEN1e  Done. Please give new version a try.

**Comment by JJAYCHEN1e** [comment]
@sethyuan It's so nice, thank you! I'll close this issue.
